apiVersion: v2
name: applications
description: Monitoring
type: application
# Follows semver, must be updated every time this chart is modified.
version: 0.0.1
# Version of the application, for display. Does not have to follow semver.
appVersion: "0.0.1"

dependencies:
  - name: kube-prometheus-stack
    version: 45.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 4.6.1
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.9.0
    repository: https://grafana.github.io/helm-charts
