kube-prometheus-stack:
  # Disable kubeproxy monitoring, since cilium is deployed with
  # kubeproxy-free mode.
  kubeProxy:
    enabled: false
    service:
      enabled: false
    serviceMonitor:
      enabled: false
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: ceph-rbd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ceph-rbd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  grafana:
    additionalDataSources:
      - name: Loki
        editable: false
        orgId: 1
        type: loki
        uid: loki
        url: "http://loki-gateway.logging.svc.cluster.local/"
        version: 1

