kube-prometheus-stack:
  # Disable kubeproxy monitoring, since cilium is deployed with
  # kubeproxy-free mode.
  kubeProxy:
    enabled: false
    service:
      enabled: false
    serviceMonitor:
      enabled: false
  prometheus:
