kube-prometheus-stack:
  # Disable kubeproxy monitoring, since cilium is deployed with
  # kubeproxy-free mode.
  kubeProxy:
    enabled: false
    service:
      enabled: false
    serviceMonitor:
      enabled: false
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: ceph-rbd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ceph-rbd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  
