apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- monitoring-crds.yaml

patches:
- path: argocd-cm.yaml

images:
- name: quay.io/argoproj/argocd
  newTag: v2.11.2
