apiVersion: v2
name: applications
description: Storage Cluster
type: application
# Follows semver, must be updated every time this chart is modified.
version: 0.0.1
# Version of the application, for display. Does not have to follow semver.
appVersion: "0.0.1"

dependencies:
  - name: rook-ceph-cluster
    version: v1.13.3
    repository: https://charts.rook.io/release
