- name: Initialize k8s cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --skip-token-print --skip-phases=bootstrap-token,show-join-command,addon/kube-proxy >> cluster-initialized
  args:
    chdir: $HOME
    creates: cluster-initialized
  when:
    # Only the first kubemaster actually runs the full init
    - inventory_hostname == play_hosts[0]

# TODO: join the other kubemasters once HAProxy for the API is installed

# - name: Get token
#   ansible.builtin.include_role:
#     name: kubeadm-get-token
#     public: true

# - name: Join cluster
#   shell: "{{ hostvars[play_hosts[0]].join_command }} --control-plane >> node-joined"
#   args:
#     chdir: $HOME
#     creates: node-joined
#   when:
#     # Join all nodes except the first kubemaster
#     - inventory_hostname != play_hosts[0]
