- name: "{{ target_vm_name }} | wait for cloud-init"
  community.general.cloud_init_data_facts:
    filter: status
  register: res
  until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
  retries: 50
  delay: 5
  delegate_to: "{{ target_vm_name }}"

