# Hostname for accessing the Proxmox API. Defaults to localhost.
proxmox_api_host: "127.0.0.1"

# User for which the API token and secret apply. By default assumed to
# be root, provided by the local PAM instance.
proxmox_api_user: "root@pam"

# Path where data such as images can be stored. Defaults to the local
# storage of the node, but could be a path such as
# `/mnt/pve/cephfs` if distributed storage is enabled.
proxmox_storage_id: "local"
proxmox_storage_path: "/var/lib/vz"

# Storage type where disk volumes are stored. Defaults to the local
# ZFS pool, but could be `cluster-ceph` if distributed storage is
# enabled.
proxmox_volume_storage: "local-zfs"

# Name of the API tokens for Proxmox. There should be no need to
# change this, but can be customized if desired.
base_proxmox_api_token_id: "root-ansible"
