- name: "kubemaster"
  include_role:
    name: vm-from-template
  vars:
    target_vm_id: "1001"
    target_vm_name: "kubemaster"
    target_vm_host: "parallax-1"
    template_vm_name: "debian-11-template"
    template_vm_host: "parallax-1"
- name: "worker-01"
  include_role:
    name: vm-from-template
  vars:
    target_vm_id: "1005"
    target_vm_name: "worker-01"
    target_vm_host: "parallax-1"
    template_vm_name: "debian-11-template"
    template_vm_host: "parallax-1"
