- name: "Create all VMs"
  include_role:
    name: vm-from-template
  vars:
    target_vm_id: "{{ vm.vm_id }}"
    target_vm_name: "{{ vm.name }}"
    target_vm_host: "{{ vm.host }}"
    template_vm_name: "debian-11-template"
    template_vm_host: "parallax-1"
  with_items: "{{ all_vms }}"
  loop_control:
    loop_var: vm
