traefik:
  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enable: true
        additionalLabels:
          release: "monitoring"
  tlsStore:
    default:
      defaultCertificate:
        secretName: star-voidloaf-com-crt-secret
