- name: Install samba packages
  ansible.builtin.apt:
    pkg:
      - samba
      - samba-client
      - samba-vfs-modules

- name: Install sudo
  ansible.builtin.apt:
    pkg:
      - sudo

- name: Install smbpasswd sudoers file
  ansible.builtin.template:
    src: smbpasswd.j2
    dest: /etc/sudoers.d/smbpasswd
    mode: '0440'

- name: Get existing samba users
  block:
    - name: Fetch users with pdbedit
      ansible.builtin.shell: "pdbedit -L | cut -d: -f1"
      register: response
      changed_when: false
    - name: Set user facts
      ansible.builtin.set_fact:
        existing_users: "{{ response.stdout | split('\n') }}"

- name: Set initial smbpasswd for users
  ansible.builtin.command:
    argv:
      - smbpasswd
      - -a
      - -n
      - "{{item}}"
  with_items: "{{ users | map(attribute='username') | difference(existing_users) }}"

- name: Install samba config
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart smbd
