- name: Install samba packages
  ansible.builtin.apt:
    pkg:
      - samba
      - samba-client
      - samba-vfs-modules

- name: Install samba config
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart smbd
