# Import github variables from the common role
- name: "Import github variables"
  ansible.builtin.include_role:
    name: github
    public: true

- name: "Create all VMs"
  include_role:
    name: vm-from-template
  vars:
    target_vm_id: "{{ vm.vm_id }}"
    target_vm_name: "{{ vm.name }}"
    target_vm_host: "{{ vm.host }}"
    target_vm_ip: "{{ vm.ip }}/24"
    template_vm_name: "debian-12-template"
    template_vm_host: "parallax-1"
  with_items: "{{ all_vms }}"
  loop_control:
    loop_var: vm
