- name: Install sanoid
  ansible.builtin.apt:
    pkg:
      - sanoid

- name: Ensure /etc/sanoid exists
  ansible.builtin.file:
    name: /etc/sanoid
    state: directory
          
- name: Install sanoid.conf
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf

