apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-api
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 4 }}
