- name: Import config variables
  ansible.builtin.include_role:
    name: proxmox-api
    public: true

- name: "Stop all VMs"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_default_behavior: "no_defaults"
    vmid: "{{ vm.vm_id }}"
    node: "{{ vm.host }}"
    force: true
    state: stopped
  with_items: "{{ all_vms }}"
  loop_control:
    loop_var: vm
  failed_when: false

- name: "Destroy all VMs"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_default_behavior: "no_defaults"
    vmid: "{{ vm.vm_id }}"
    node: "{{ vm.host }}"
    state: absent
  with_items: "{{ all_vms }}"
  loop_control:
    loop_var: vm
