all:
  hosts:
    medium-format:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.120
      home_dataset: rpool/home
      storage_dataset: rpool/film/Users
    large-format:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.118
      home_dataset: rpool/home
      storage_dataset: exposure/film/Users
  children:
    nas:
      hosts:
        medium-format:
        large-format:
  
