all:
  hosts:
    medium-format:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.120
      home_dataset: rpool/home
      storage_dataset: rpool/film/Users
    large-format:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.1.118
      home_dataset: rpool/home
      storage_dataset: exposure/film/Users
  children:
    nas:
      hosts:
        medium-format:
        large-format:
  vars:
    users:
      - username: achernya
        uid: 1000
        gecos: "Alex Chernyakhovsky,,,"
      - username: madars
        uid: 1008
        gecos: "Madars Virza,,,"
      - username: slz
        uid: 1013
        github: vulpicastor
        gecos: "Lizhou Sha,,,"
    shares:
      - Books
      - Music
      - Software
      - Videos
