apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: alex@achernya.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        acmeDNS:
          host: http://certs-acme-dns-api.certs.svc.cluster.local:8080
          accountSecretRef:
            name: acme-dns-creds
            key: acmedns.json
