# Import proxmox API variables from the common role
- name: "{{ target_vm_name }} | import config variables"
  ansible.builtin.include_role:
    name: proxmox-api
    public: true

- name: "{{ target_vm_name }} | clone from base VM"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_default_behavior: "no_defaults"
    name: "{{ target_vm_name }}"
    clone: "{{ template_vm_name }}"
    format: "unspecified"
    full: true
    newid: "{{ target_vm_id }}"
    node: "{{ template_vm_host }}"
    target: "{{ target_vm_host }}"

- name: "{{ target_vm_name }} | render cloud-init config"
  vars:
    ansible_playbook: "cluster-bootstrap"
  ansible.builtin.template:
    dest: "{{ proxmox_storage_path }}/snippets/{{ target_vm_id }}-cloudinit.yml"
    src: cloud-init.yml.j2

- name: "{{ target_vm_name }} | update VM config for cloud-init"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_default_behavior: "no_defaults"
    vmid: "{{ target_vm_id }}"
    node: "{{ target_vm_host }}"
    update: true
    cicustom: "vendor={{ proxmox_storage_id }}:snippets/{{ target_vm_id }}-cloudinit.yml"
    ipconfig:
      ipconfig0: "gw={{ target_vm_ip | ipaddr('network/prefix') | ipaddr('1') | ipaddr('address') }},ip={{ target_vm_ip }}"

- name: "{{ target_vm_name }} | start VM"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    proxmox_default_behavior: "no_defaults"
    vmid: "{{ target_vm_id }}"
    node: "{{ target_vm_host }}"
    state: started
