apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: certs
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kubernetes/certs
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   selfHeal: true
    #   prune: true
