apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    # Monitoring CRDs have to be done very early, otherwise other helm
    # charts that try to create ServiceMonitor resources will fail.
    argocd.argoproj.io/sync-wave: "-8900"
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/kube-prometheus-stack/crds/ 
    repoURL: https://github.com/prometheus-community/helm-charts.git
    # Keep this in sync with the value inside kubernetes/monitoring/Chart.yaml
    targetRevision: kube-prometheus-stack-45.0.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
